version: "3.8"
services:
  d-planeos-website:
    image: nginx:alpine
    container_name: dplaneos-website
    hostname: dplaneos-website
    restart: unless-stopped
    ports:
      - ${WEBSITE_PORT:-8080}:80
    volumes:
      - /media/mainpool/nginx/dplaneos-website/website:/usr/share/nginx/html:rw
      - /media/mainpool/nginx/dplaneos-website/docker-nginx.conf:/etc/nginx/conf.d/default.conf:rw
    environment:
      TZ: Europe/Berlin
      GITHUB_USERNAME: ${GITHUB_USERNAME:-yourusername}
      WEBSITE_DOMAIN: ${WEBSITE_DOMAIN:-your-domain.com}
    labels:
      com.dockge.description: D-PlaneOS Marketing Website - Static site hosting
      com.dockge.icon: 🚀
      com.dockge.docs: https://github.com/${GITHUB_USERNAME:-yourusername}/dplaneos
      com.dockge.health.endpoint: http://localhost:${WEBSITE_PORT:-8080}
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost/
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - web
networks:
  web:
    name: web
    external: false
